// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbwevpmcuvawykfyrxvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indid2V2cG1jdXZhd3lrZnlyeHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NTA0MjcsImV4cCI6MjA4NzQyNjQyN30.aNSK_xoj7cyPPcYubEoO5YvG-_ZH44dKBywm9CCXrso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});